config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'

  get 'rules', to: 'pages#rules'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get '/register', to: 'users#new'

  resources :cards, only: [:new, :create, :edit, :update, :show, :index] do

    resources :comments, only: [:create]

  end

  resources :card_types, only: [:new, :create, :edit, :update]

  resources :card_subtypes, only: [:new, :create, :edit, :update]

  resources :factions, except: [:destroy]

  resources :expansions, except: [:destroy]

  resources :users, only: [:show, :create, :edit, :update, :new]


end

app/views/shared/_error_messages.html.haml
- if obj.errors.any?
  .row
    .col-md-8
      %div(class="alert alert-danger alert-dismissible" role="alert")
        %button(type="button" class="close" data-dismiss="alert" aria-label="Close")
          %span(aria-hidden="true") &times;
        %h5 Oops looks like something isn't quite right:
        %ul
          - obj.errors.full_messages.each do |msg|
            %li= msg

app/views/shared/_header.html.haml
#navbar-container 
  %nav.navbar.navbar-inverse
    .container-fluid
      .navbar-header
        = link_to "Amaranthe CCG", root_path, class: "navbar-brand"
      %ul.nav.navbar-nav
        %li
          = link_to "Cards", cards_path
        %li
          = link_to "Rules", rules_path
        - if logged_in?  && current_user.is_super_user?
          %li.dropdown
            %a.dropdown-toggle( data-toggle="dropdown" href="#" id="dlabel" )
              Create a...
              %span.caret
            %ul.dropdown-menu( role="menu" aria-labelledby="dlabel" )
              %li{ role: "presentation" }
                = link_to "Card", new_card_path, { role: "menuitem" }
              %li.divider
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Faction", "#", role: "menuitem"
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Expansion", new_expansion_path, { role: "menuitem" }
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Card Type", new_card_type_path, { role: "menuitem" }
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Card Subtype", new_card_subtype_path, { role: "menuitem" }
          %li.dropdown
            %a.dropdown-toggle( data-toggle="dropdown" href="#" id="dlabel" )
              Make a change to...
              %span.caret
            %ul.dropdown-menu( role="menu" aria-labelledby="dlabel" )
              %li{ role: "presentation" }
                = link_to "Your Profile", edit_user_path(current_user), role: "menuitem"
              %li{ role: "presentation" }
                = link_to "Cards", "#", { role: "menuitem" }
              %li.divider
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Factions", "#", role: "menuitem"
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Expansions", "#", { role: "menuitem" }
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Card Types", "#", { role: "menuitem" }
              %li{ role: "presentation", class: ( "disabled" unless current_user.is_admin? ) }
                = link_to "Card Subtypes", "#", { role: "menuitem" }
      %ul.nav.navbar-nav.navbar-right
        - if !logged_in?
          %li
            = link_to register_path do
              Sign Up
              %span.glyphicon.glyphicon-user
          %li
            = link_to sign_in_path do
              Login
              %span.glyphicon.glyphicon-log-in
        - else
          %li
            = link_to sign_out_path do
              Logout
              %span.glyphicon.glyphicon-log-out

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}" role="alert")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)