config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'

  get 'rules', to: 'pages#rules'

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  get 'sign_out', to: 'sessions#destroy'

  get '/register', to: 'users#new'

  resources :cards, only: [:new, :create, :edit, :update, :show, :index] do

    resources :comments, only: [:create]

  end

  resources :card_types, only: [:new, :create, :edit, :update]

  resources :card_subtypes, only: [:new, :create, :edit, :update]

  resources :factions, except: [:destroy]

  resources :expansions, except: [:destroy]

  resources :users, only: [:show, :create, :edit, :update, :new]


end

app/models/card.rb
class Card < ActiveRecord::Base
  include SlugableCtrembley
  
  belongs_to :expansion
  belongs_to :faction
  has_and_belongs_to_many :card_types
  has_and_belongs_to_many :card_subtypes
  has_many :comments

  validates :name, presence: true, uniqueness: true

  slugable_column :name
end

app/models/card_type.rb
class CardType < ActiveRecord::Base
  has_and_belongs_to_many :cards
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:edit, :update, :show]
  before_action :require_user
  before_action :can_create?, only: [:edit, :udpate]

  def new
    @card = Card.new
  end

  def create
    set_card_type
    set_card_subtypes
    @card = Card.new(card_params)

    if @card.save
      flash[:success] = "New Card created"
      redirect_to new_card_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    set_card_type
    set_card_subtypes

    if @card.update(card_params)
      flash[:success] = "Card updated successfully"
      redirect_to card_path(@card)
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
  end

  def index
    @cards = Card.all
  end

  private

  def card_params
    params.require(:card).permit!
  end

  def set_card
    @card = Card.find_by(slug: params[:id])
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action." 
      redirect_to sign_in_path
    end
  end

  def can_create?
    if !current_user.is_super_user?
      flash[:danger] = "Sorry, you have insufficient privlages to perform that action"
      redirect_to root_path
    end
  end

  def set_card_subtypes
    if params[:card][:card_subtypes].size != 1
      card_subtypes = []

      1.upto(params[:card][:card_subtypes].size-1) do |x|
        card_subtypes << CardSubtype.find(params[:card][:card_subtypes][x])
      end

      return params[:card][:card_subtypes] = card_subtypes
    end
    params[:card][:card_subtypes] = []
  end

  def set_card_type
    params[:card][:card_types] = [CardType.find(params[:card][:card_types])]
  end
end

app/views/cards/_form.html.haml
- if @card.errors.any?
  = render 'shared/error_messages', obj: @card
%section#card-form-container
  .row
    .col-sm-10.col-sm-offset-1
      = bootstrap_form_for @card, html: { class: "form-horizontal" } do |f|
        %header
          %h1 Please enter the card details
        %fieldset#card_inputs
          = f.text_field :name, label: "Card Name"
          = f.collection_select :expansion_id, Expansion.all, :id, :name
          = f.collection_select :faction_id, Faction.all, :id, :name
          = f.collection_select :card_types, CardType.all, :id, :name, label: "Card Type"
          .well
            = f.collection_check_boxes :card_subtypes, CardSubtype.all, :id, :name, label: "Card Subtypes"
          = f.text_field :cost, label: "Cost"
          = f.text_area :text1, label: "1st Ability"
          = f.text_area :text2, label: "2nd Ability"
          = f.text_area :text3, label: "3rd Ability"
          = f.text_area :text4, label: "4th Ability"
          = f.text_area :text5, label: "5th Ability"
          = f.text_area :text6, label: "6th Ability"
          = f.text_area :text7, label: "7th Ability"
          = f.text_area :text8, label: "8th Ability"
        %fieldset.actions.control-group.col-sm-1.controls
          %input( type="submit" value="Submit" class="btn btn-primary" )

app/views/cards/index.html.haml
%section#card_index
  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th Card Name
        %th Card Type
        %th Comments
        %th Last Updated
    %tbody
      - @cards.each do |card|
        %tr
          %td
            = link_to card.name, card_path(card)
          %td
            = card.card_types.first.name
          %td
            = card.comments.count
          %td
            - if card.comments.count == 0
              = fix_date(card.updated_at)
            - else
              = fix_date(card.comments.last.updated_at)

app/views/cards/show.html.haml
%section#show_card_container
  %h2
    = @card.name

  - if logged_in? && current_user.is_admin?
    = link_to "Edit this card", edit_card_path(@card)

  %section#card_box
    %div#card_border
      #card_name
        = @card.name
        #card_cost
          = @card.cost
      #card_art
        Card Art Here
      #card_type
        - if @card.card_subtypes.any?
          = "#{@card.card_types.first.name} - "
          - @card.card_subtypes.each do |cst|
            = "#{cst.name} "
        - else
          = @card.card_types.first.name
        %span.glyphicon.glyphicon-tower#card_icon 
      #card_text
        %ul
          - if @card.text1 != ""
            %li
              = @card.text1
          - if @card.text2 != ""
            %li
              = @card.text2
          - if @card.text3 != ""
            %li
              = @card.text3
          - if @card.text4 != ""
            %li
              = @card.text4
          - if @card.text5 != ""
            %li
              = @card.text5
          - if @card.text6 != ""
            %li
              = @card.text6
          - if @card.text7 != ""
            %li
              = @card.text7
          - if @card.text8 != ""
            %li
              = @card.text8

  %hr

  - if logged_in?
    = render 'comments/form'

  %hr  

  - @card.comments.each do |comment|
    = render 'comments/comment', comment: comment